### ISSUE TITLE
No new sensors

### ISSUE THREAD

**Issue by robbinonline** [marcelwestrahome/home-assistant-niu-component#2]
I have installed this component added the config as described.
I only see this in my log and no new sensors: 2020-07-14 13:02:47 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for niu which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by marcelwestrahome** [comment]
Q1; are you an experienced HA user ?
Q2: are your sure you do not have sensor.niu_scooter_**your scooter name** sensors

**Comment by marcelwestrahome** [comment]
sensor.niu_scooter_xxxx_battery_charge

**Comment by robbinonline** [comment]
Q1. Yes
Q2. Nothing

I used id 0 and for country i try NL, Netherlands and The Netherlands.
Found in the logs: Invalid entity id: sensor.niu_scooter_Batmobiel_battery_charge

**Comment by marcelwestrahome** [comment]
mm i think the problem is the capital in your scooter name. HA does not allow capitals in entity ids. I take the name of the scooter from niu and use it to create the entity ids. Maybe I have to add functionality to be sure creating valid entity ids.

If you change your name in batmobiel instead of Batmobiel it had to work.

**Comment by robbinonline** [comment]
Yes that solved the issue! Thanks the support
